"use client";
import { useState } from "react";
import { Sparkle, X, Warning, Coin } from "@phosphor-icons/react";
import styles from "./AICloneConfirmModal.module.css";

interface Props {
  isOpen: boolean;
  onClose: () => void;
  onConfirm: () => void;
  gameTitle: string;
  userCredits: number;
  hasBetaAccess: boolean;
  betaStatus: "pending" | "approved" | "rejected" | null;
}

export default function AICloneConfirmModal({
  isOpen,
  onClose,
  onConfirm,
  gameTitle,
  userCredits,
  hasBetaAccess,
  betaStatus,
}: Props) {
  const [isProcessing, setIsProcessing] = useState(false);
  const creditsRequired = 10;
  const hasEnoughCredits = userCredits >= creditsRequired;

  if (!isOpen) return null;

  const handleConfirm = async () => {
    setIsProcessing(true);
    await onConfirm();
    setIsProcessing(false);
  };

  // User has not applied for beta access
  if (!hasBetaAccess) {
    return (
      <div className={styles.modalOverlay} onClick={onClose}>
        <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
          <button className={styles.closeButton} onClick={onClose}>
            <X size={24} />
          </button>

          <div className={styles.modalHeader}>
            <Sparkle size={48} weight="fill" className={styles.aiIcon} />
            <h2 className={styles.modalTitle}>Beta Access Required</h2>
          </div>

          <div className={styles.modalBody}>
            <div className={styles.warningBox}>
              <Warning size={24} weight="fill" />
              <p>
                This game was generated by <strong>Pregúntame Wizard (AI)</strong>. Cloning
                AI-generated games requires beta access.
              </p>
            </div>

            <p className={styles.modalText}>
              You haven't applied for beta access yet. Apply now to get{" "}
              <strong>500 free credits</strong> and access to AI features!
            </p>

            <div className={styles.creditsInfo}>
              <Coin size={20} weight="fill" />
              <span>
                Cloning this AI game costs: <strong>10 credits</strong>
              </span>
            </div>
          </div>

          <div className={styles.modalActions}>
            <button className={styles.cancelButton} onClick={onClose}>
              CANCEL
            </button>
            <button
              className={styles.applyButton}
              onClick={() => (window.location.href = "/beta-access")}
            >
              APPLY FOR BETA
            </button>
          </div>
        </div>
      </div>
    );
  }

  // User has applied but status is pending
  if (betaStatus === "pending") {
    return (
      <div className={styles.modalOverlay} onClick={onClose}>
        <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
          <button className={styles.closeButton} onClick={onClose}>
            <X size={24} />
          </button>

          <div className={styles.modalHeader}>
            <Sparkle size={48} weight="fill" className={styles.aiIcon} />
            <h2 className={styles.modalTitle}>Beta Access Pending</h2>
          </div>

          <div className={styles.modalBody}>
            <div className={styles.warningBox}>
              <Warning size={24} weight="fill" />
              <p>
                This game was generated by <strong>Pregúntame Wizard (AI)</strong>. Cloning
                AI-generated games requires approved beta access.
              </p>
            </div>

            <p className={styles.modalText}>
              Your beta access request is currently <strong>pending review</strong>. Please wait for
              approval to clone AI-generated games.
            </p>

            <p className={styles.supportText}>
              Need immediate access? Contact us at{" "}
              <a href="mailto:info@preguntame.eu">info@preguntame.eu</a>
            </p>
          </div>

          <div className={styles.modalActions}>
            <button className={styles.cancelButton} onClick={onClose}>
              CLOSE
            </button>
          </div>
        </div>
      </div>
    );
  }

  // User has been rejected or has insufficient credits
  if (betaStatus === "rejected" || !hasEnoughCredits) {
    return (
      <div className={styles.modalOverlay} onClick={onClose}>
        <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
          <button className={styles.closeButton} onClick={onClose}>
            <X size={24} />
          </button>

          <div className={styles.modalHeader}>
            <Sparkle size={48} weight="fill" className={styles.aiIcon} />
            <h2 className={styles.modalTitle}>
              {betaStatus === "rejected" ? "Beta Access Denied" : "Insufficient Credits"}
            </h2>
          </div>

          <div className={styles.modalBody}>
            <div className={styles.errorBox}>
              <Warning size={24} weight="fill" />
              <p>
                {betaStatus === "rejected"
                  ? "Your beta access has been revoked or denied."
                  : `You need ${creditsRequired} credits to clone this AI-generated game, but you only have ${userCredits} credits.`}
              </p>
            </div>

            <p className={styles.modalText}>
              To proceed with cloning AI-generated games, please contact our support team.
            </p>

            <p className={styles.supportText}>
              Email us at <a href="mailto:info@preguntame.eu">info@preguntame.eu</a>
            </p>
          </div>

          <div className={styles.modalActions}>
            <button className={styles.cancelButton} onClick={onClose}>
              CLOSE
            </button>
            <a href="mailto:info@preguntame.eu" className={styles.contactButton}>
              CONTACT SUPPORT
            </a>
          </div>
        </div>
      </div>
    );
  }

  // User has approved access and enough credits
  return (
    <div className={styles.modalOverlay} onClick={onClose}>
      <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
        <button className={styles.closeButton} onClick={onClose}>
          <X size={24} />
        </button>

        <div className={styles.modalHeader}>
          <Sparkle size={48} weight="fill" className={styles.aiIcon} />
          <h2 className={styles.modalTitle}>Clone AI Game</h2>
        </div>

        <div className={styles.modalBody}>
          <div className={styles.infoBox}>
            <Sparkle size={20} weight="fill" />
            <p>
              This game was generated by <strong>Pregúntame Wizard (AI)</strong>.
            </p>
          </div>

          <p className={styles.modalText}>
            You're about to clone "<strong>{gameTitle}</strong>" to your account.
          </p>

          <div className={styles.creditsDisplay}>
            <div className={styles.creditsRow}>
              <span>Your current credits:</span>
              <span className={styles.creditsValue}>
                <Coin size={18} weight="fill" />
                {userCredits}
              </span>
            </div>
            <div className={styles.creditsRow}>
              <span>Cost to clone:</span>
              <span className={styles.creditsCost}>
                <Coin size={18} weight="fill" />-{creditsRequired}
              </span>
            </div>
            <div className={styles.divider}></div>
            <div className={styles.creditsRow}>
              <span>Remaining credits:</span>
              <span className={styles.creditsRemaining}>
                <Coin size={18} weight="fill" />
                {userCredits - creditsRequired}
              </span>
            </div>
          </div>

          <p className={styles.confirmText}>Are you sure you want to continue?</p>
        </div>

        <div className={styles.modalActions}>
          <button className={styles.cancelButton} onClick={onClose} disabled={isProcessing}>
            CANCEL
          </button>
          <button className={styles.confirmButton} onClick={handleConfirm} disabled={isProcessing}>
            {isProcessing ? "CLONING..." : `CONFIRM (${creditsRequired} CREDITS)`}
          </button>
        </div>
      </div>
    </div>
  );
}
